IMAGE = "swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/agentscope/copaw:v0.0.7-linuxarm64"
[[mutipaws]]
CONTAINER_NAME = "copaw"
PORT = "8088"
NETWORK_MODE = "host"

[[mutipaws]]
CONTAINER_NAME = "copaw2"
PORT = "8089"
NETWORK_MODE = "bridge"

[[mutipaws]]
CONTAINER_NAME = "copaw3"
PORT = "8090"
NETWORK_MODE = "bridge"


